import './globals.css'

export const metadata = {
  title: 'Multi-step form',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className="md:h-screen w-screen md:flex md:justify-center md:items-center">
      <body className="bg-blue-50 md:flex md:justify-center xl:text-xl">
        {children}
      </body>
    </html>
  )
}
