import './globals.css'

export const metadata = {
  title: 'Multi-step form',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className="bg-blue-50">
        {children}
      </body>
    </html>
  )
}
